### PR TITLE
DNS Config is not saved properly

### PR DESCRIPTION
**Pull request by sparsick**
#126 

After refactoring the POJO classes I forget to rename the field names in the config.jelly and of course after refactoring I didn't retest it manually 🙈 . This PR fixes it.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by sparsick** [comment]
@timja Do you have a hint for me how to write an automated test to avoid such kind of mistakes?

**Comment by timja** [comment]
> @timja Do you have a hint for me how to write an automated test to avoid such kind of mistakes?

`configRoundTrip` should do it, https://www.jenkins.io/doc/developer/testing/#configuration-round-trip-testing

**Comment by sparsick** [comment]
Thanks, let me add a test (unfortunately I will find in the afternoon time for it. ) before you merge it.

**Comment by sparsick** [comment]
The JenkinsRule doesn't have a configRoundTrip method for the cloud configuration page. Therefore, I try to simulate it.

**Pull request merged**
